<?php

/**
 * @file
 * Stanford Alt Check Module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function stanford_alt_check_ctools_plugin_api($owner, $api) {
  if ($owner == "context" && $api == "context") {
    return array("version" => 3);
  }
}

/**
 * Implements hook_menu().
 */
function stanford_alt_check_menu() {
  $items = array();
  $items['admin/content/images'] = array(
    'title' => "Images",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_alt_check_image_uploads'),
    'file' => 'stanford_alt_check.forms.inc',
    'access arguments' => array('access content overview'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/images/uploads'] = array(
    'title' => "Image Uploads",
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/content/images/wysiwyg'] = array(
    'title' => "WYSIWYG Images",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_alt_check_image_wysiwyg'),
    'file' => 'stanford_alt_check.forms.inc',
    'access arguments' => array('access content overview'),
    'type' => MENU_LOCAL_TASK,
  );

  // Manage Content Menu Items.
  $items['admin/images'] = array(
    'title' => "Manage Images",
    'page callback' => 'stanford_alt_check_images',
    'file' => 'stanford_alt_check.forms.inc',
    'access arguments' => array('access content overview'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-manage-content-by-type',
  );
  $items['admin/images/uploads'] = array(
    'title' => "Manage Image Uploads",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_alt_check_image_uploads'),
    'file' => 'stanford_alt_check.forms.inc',
    'access arguments' => array('access content overview'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-manage-content-by-type',
  );
  $items['admin/images/wysiwyg'] = array(
    'title' => "Manage WYSIWYG Images",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_alt_check_image_wysiwyg'),
    'file' => 'stanford_alt_check.forms.inc',
    'access arguments' => array('access content overview'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-manage-content-by-type',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function stanford_alt_check_theme($existing, $type, $theme, $path) {
  return array(
    'stanford_alt_check_image_uploads' => array(
      'render element' => 'form',
      'file' => 'stanford_alt_check.theme.inc',
    ),
    'stanford_alt_check_image_wysiwyg' => array(
      'render element' => 'form',
      'file' => 'stanford_alt_check.theme.inc',
    ),
  );
}

/**
 * Gets all entities with missing wywisyg image alts.
 *
 * @return array
 *   Entities with missing alt attributes in wysiwyg fields.
 */
function stanford_alt_check_get_wysiwyg() {
  $image_fields = stanford_alt_check_get_wysiwyg_fields();
  $return_data = array();
  foreach ($image_fields as $field) {

    $query = new EntityFieldQuery();
    $query->fieldCondition($field['field_name'], 'value', '%<img%', 'like');
    $results = $query->execute();

    foreach ($results as $type => $entities) {
      foreach (entity_load($type, array_keys($entities)) as $id => $entity) {

        $field_items = field_get_items($type, $entity, $field['field_name']);
        if (!$field_items) {
          continue;
        }

        list(, , $bundle) = entity_extract_ids($type, $entity);
        foreach ($field_items as $delta => $item) {
          if ($images = stanford_alt_check_get_wysiwyg_images($item)) {
            $return_data[$field['field_name']][$type][$bundle][$id][$delta] = $images;
          }
        }
      }
    }
  }
  return $return_data;
}

/**
 * Get all fields that have text_process as true.
 *
 * @return array
 *   All fields with possible html.
 */
function stanford_alt_check_get_wysiwyg_fields() {
  $fields = array();
  $wywisyg_field_types = array('text', 'text_long', 'text_with_summary');
  foreach (field_info_fields() as $field) {
    if (in_array($field['type'], $wywisyg_field_types)) {
      foreach ($field['bundles'] as $type => $bundles) {
        foreach ($bundles as $bundle) {
          $instance = field_info_instance($type, $field['field_name'], $bundle);
          if ($instance['settings']['text_processing']) {
            $fields[] = $field;
          }
        }
      }
    }
  }
  return $fields;
}

/**
 * Process the field item data to get all images in the html.
 *
 * @param array $field_item
 *   Field data array.
 *
 * @return array
 *   Keyed array of images with the key as the position of the image in html.
 */
function stanford_alt_check_get_wysiwyg_images(array $field_item) {
  $images = array();

  $dom = new DOMDocument();
  $dom->loadHTML($field_item['value']);
  /** @var DOMElement $img_element */
  foreach ($dom->getElementsByTagName('img') as $img_position => $img_element) {

    // Parse the path to get the file uri.
    $img_src = trim($img_element->getAttribute('src'), '/?');
    $img_src = substr($img_src, 0, strpos($img_src, '?'));

    if (strpos($img_src, '/styles/') !== FALSE) {

      // Image style derivative.
      $src = explode('/', $img_src);
      $style_pos = array_search('styles', $src);
      $image_name = '//' . implode('/', array_slice($src, $style_pos + 3));
    }
    else {

      // Original Image.
      $image_name = str_replace(variable_get('file_private_path'), '', $img_src);
      $image_name = str_replace(variable_get('file_public_path'), '', $image_name);
      $image_name = "/$image_name";
    }

    // Try to find in the file managed table.
    $fid = db_select('file_managed', 'f')
      ->fields('f', array('fid'))
      ->condition('uri', "%$image_name%", 'like')
      ->execute()->fetchField();

    if ($fid && ($image = file_load($fid))) {
      $image->alt = $img_element->getAttribute('alt');
    }
    $images[$img_position] = (array) $image;
  }
  return $images;
}

/**
 * Gets the fields and entities with missing alt attributes.
 *
 * @return array
 *   Keyed array of fields and entities with missing alt attributes.
 *   First set of array keys are the field machine name used. Second key is the
 *   entity type. Then 3rd key is the entity id. The value of the 3rd key is the
 *   entity to be used.
 *   Ex. array('field_image' => array('node' => array(10 => [Node Object])))
 */
function stanford_alt_check_upload_entities() {
  $image_fields = array();
  // Get all image type fields.
  foreach (field_info_fields() as $field) {
    if ($field['type'] == 'image') {
      $image_fields[] = $field;
    }
  }

  $return_data = array();
  // Gets all entities where the image alt attribute is missing.
  foreach ($image_fields as $field) {
    $query = new EntityFieldQuery();
    $query->fieldCondition($field['field_name'], 'fid', '0', '>=');
    $results = $query->execute();

    foreach ($results as $type => $result_entities) {
      foreach (entity_load($type, array_keys($result_entities)) as $entity) {
        list($id, , $bundle) = entity_extract_ids($type, $entity);
        $return_data[$field['field_name']][$type][$bundle][$id] = $entity;
      }
    }
  }
  return $return_data;
}

/**
 * Menu callback to display all entities with missing alt attributes.
 *
 * @return array
 *   Render array with the table.
 */
function stanford_alt_check_images() {
  $output = array();
  $output['message'] = array(
    '#markup' => t('<p>Below are a list of entities that have an image with a missing ALT attribute. Please view and edit the entity to correct these errors.</p>'),
  );
  $rows = stanford_alt_check_build_rows(stanford_alt_check_get_wysiwyg());
  $rows = stanford_alt_check_build_rows(stanford_alt_check_upload_entities(), $rows);

  // Sort based on get parameters.
  usort($rows, 'stanford_alt_check_sort_rows');

  // Pager.
  $current_page = pager_default_initialize(count($rows), 25);
  $chunks = array_chunk($rows, 25, TRUE);
  $output['table'] = array(
    '#theme' => 'table',
    '#header' => array(
      array('data' => t('Entity'), 'field' => 'Entity'),
      array('data' => t('Field'), 'field' => 'Field'),
      array('data' => t('Entity Type'), 'field' => 'Entity Type'),
      array('data' => t('Bundle'), 'field' => 'Bundle'),
    ),
    '#rows' => $chunks[$current_page],
  );
  $output['pager'] = array(
    '#theme' => 'pager',
  );
  return $output;
}

/**
 * Process the entity list to build table rows.
 *
 * @param array $data
 *   Entity data to parse.
 * @param array $rows
 *   Existing rows to add to.
 *
 * @return array
 *   Simple array to be used in tables.
 */
function stanford_alt_check_build_rows(array $data, array $rows = array()) {
  foreach ($data as $field_name => $types) {
    foreach ($types as $type => $bundles) {
      foreach ($bundles as $bundle => $entities) {
        $field_instance = field_info_instance($type, $field_name, $bundle);
        $field_name = $field_instance['label'];

        foreach ($entities as $entity) {
          if (!($item = stanford_alt_check_get_host($entity, $type))) {
            continue;
          }
          list($e, $t, $eid, , $ebundle) = $item;
          if ($t == 'bean') {
            $title = $e->label;
          }
          else {
            $title = $e->title;
          }

          $path = entity_uri($t, $e);
          $e_info = entity_get_info($t);

          // Concat other fields to the field list.
          if (isset($rows["$t-$eid"])) {
            $efields = explode('; ', $rows["$t-$eid"]['Field']);
            if (!in_array($field_name, $efields)) {
              $efields[] = $field_name;
            }
            $rows["$t-$eid"]['Field'] = implode('; ', $efields);
          }
          else {
            // Build row with first field.
            $rows["$type-$eid"] = array(
              'Entity' => l(t($title), $path['path']),
              'Field' => $field_name,
              'Entity Type' => $e_info['label'],
              'Bundle' => $e_info['bundles'][$ebundle]['label'],
            );
          }
        }
      }
    }
  }
  return $rows;
}

/**
 * Sort function to sort arrays with strings based on GET parameters.
 *
 * @param array $array_a
 *   Array 1 to compare.
 * @param array $array_b
 *   Array 2 to compare.
 *
 * @return int
 *   Order of the two arrays.
 */
function stanford_alt_check_sort_rows(array $array_a, array $array_b) {
  $get = drupal_get_query_parameters($_GET);

  // Check if we are to order specifically and if the keys exist to order on.
  if (isset($get['order']) && isset($array_a[$get['order']]) && isset($array_b[$get['order']])) {
    // Which direction.
    if (!isset($get['sort']) || $get['sort'] == 'asc') {
      return strcmp(strip_tags($array_a[$get['order']]), strip_tags($array_b[$get['order']]));
    }
    return strcmp(strip_tags($array_b[$get['order']]), strip_tags($array_a[$get['order']]));
  }

  // Fallback: sort by first element of each array.
  return strcmp(strip_tags($array_a[key($array_a)]), strip_tags($array_b[key($array_b)]));
}

/**
 * Recursive function that will continue down to the greates host entity.
 *
 * @param object $entity
 *   The actual entity to get host data from.
 * @param string $type
 *   The type of the entity we are inspecting.
 *
 * @return array|bool
 *   Array of host entity data or FALSE if it fails to obtain host.
 */
function stanford_alt_check_get_host($entity, $type) {
  $host_entity = $host_type = NULL;
  switch ($type) {
    case 'field_collection_item':
      // Field Collection entities: Change $host_type & $host_entity to host
      // entity.
      $host_entity = $entity->hostEntity();
      $host_type = $entity->hostEntityType();
      if (!($item = stanford_alt_check_get_host($host_entity, $host_type))) {
        return FALSE;
      }
      list($host_entity, $host_type) = $item;
      break;

    case 'paragraphs_item':
      // Paragraph Item entities: Change $host_type& $host_entityto host entity.
      // We use field query because the
      // ParagraphsItemEntity::hostEntityType() &
      // ParagraphsItemEntity::hostEntity() do not always work.
      $query = new EntityFieldQuery();
      $query->fieldCondition($entity->field_name, 'value', $entity->item_id);
      if ($results = $query->execute()) {
        $types = array_keys($results);
        $host_type = reset($types);
        $entity_loaded = entity_load($host_type, array_keys($results[$host_type]));
        $host_entity = reset($entity_loaded);
        if (!($item = stanford_alt_check_get_host($host_entity, $host_type))) {
          return FALSE;
        }
        list($host_entity, $host_type) = $item;
      }
      break;

    default:
      $host_type = $type;
      $host_entity = $entity;
      break;
  }

  if ($host_entity && $host_type) {
    list($entity_id, $vid, $bundle) = entity_extract_ids($host_type, $host_entity);
    return array($host_entity, $host_type, $entity_id, $vid, $bundle);
  }
  return FALSE;
}
